spring:
  application:
    name: "gateway"

  config:
    import:
      - classpath:application-redis.yml
      - classpath:application-logging.yml
      - classpath:application-management.yml

server:
  port: 8081
