global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway:8080' ]

  - job_name: 'domain-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'domain-service:9091' ]
