spring:
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USER:guest}
    password: ${RMQ_PWD:guest}
  application:
    name: "domain"
  data:
    mongodb:
      uri: "mongodb://mongo:27017/transaction_db"